name: formacion_flutter_estado
description: Formación de manejo de estado en Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  provider: ^3.2.0
  bloc: ^2.0.0
  flutter_bloc: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
